version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8000:80
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge