version: '3'
services:
  php:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - database
    networks:
      - app-network
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5632:5432
    volumes:
      - .docker/.data/.postgresql/13/data:/var/lib/postgresql/data
    networks:
      - app-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
